options:

  deployment:
    type: string
    description: development, staging or production
    default: production

  source_repo:
    type: string
    default: "ppa:hockeypuck/unstable"
    description: PPA repository to install Hockeypuck from.

  app_path:
    type: string
    default: /srv
    description: Base directory location for service configuration & log files.

  hkp_port:
    type: int
    default: 11371
    description: >
        Listen port for HTTP Keyserver Protocol (HKP) requests.

  recon_port:
    type: int
    default: 11370
    description: Listen port for recon gossip protocol.

  recon_allow_cidrs:
    type: string
    default: ""
    description: >
        Comma-separated list of CIDRs to allow gossip peers to connect from.
        For example, 10.0.0.0/8,192.168.0.0/16,163.15.34.10/32

  recon_gossip_interval:
    type: int
    default: 60
    description: >
        Maximum time to wait between gossip connection attempts to peers.
        The actual delay is randomized.

  recon_partners:
    type: string
    default: ""
    description: >
        Space-separated list of extra gossip peers, each of which defined by a
        comma-separated pair of <http host:port>,<recon host:port> addresses. For example,
        "10.0.0.2:11371,10.0.0.2:11370 keys.load-balanced.org:11371,163.71.23.24:11370"

  log_level:
    type: string
    description: "Log level, one of: debug, info, warning, error, fatal, panic"
    default: INFO

