#!/bin/bash

SRC=$(action-get src)
if [ -z "$SRC" ]; then
	action-fail "'src' parameter is required."
	exit 0
fi

DEST=$(action-get dest)
if [ -z "$DEST" ]; then
	action-fail "'dest' parameter is required."
	exit 0
fi

if [[ "$SRC" = "rsync://*" ]]; then
	action-set started-at=$(date)
	rsync -avr ${SRC}/ ${DEST}/
	action-set completed-at=$(date)
else
	action-fail "URL scheme $SRC not supported."
fi

