#!/bin/bash

SRC=$(action-get src)
if [ -z "$SRC" ]; then
	action-fail "'src' parameter is required."
	exit 0
fi

DEST=$(action-get dest)
if [ -z "$DEST" ]; then
	action-fail "'dest' parameter is required."
	exit 0
fi

mkdir -p ${DEST}

if [[ "$SRC" =~ "rsync://" ]]; then
	rsync -avr ${SRC}/ ${DEST}/
elif [[ "$SRC" =~ "http://" || "$SRC" =~ "ftp://" ]]; then
	cd ${DEST}
	wget -e robots=off --wait 0.25 -nH --cut-dirs=100 -r ${SRC}
else
	action-fail "URL scheme $SRC not supported."
fi

