#!/bin/bash

SRC=$(action-get src)
if [ -z "$SRC" ]; then
	action-fail "'src' parameter is required."
	exit 0
fi

DEST=$(action-get dest)
if [ -z "$DEST" ]; then
	action-fail "'dest' parameter is required."
	exit 0
fi

mkdir -p ${DEST}

if [[ "$SRC" =~ "rsync://" ]]; then
	rsync -avr ${SRC}/ ${DEST}/
else
	action-fail "URL scheme $SRC not supported."
fi

